### ISSUE TITLE
Pendulum Example, continuous action space example for DDPG

### ISSUE THREAD

**Issue by NarasimhaM3101** [facebookresearch/ReAgent#116]
hi, 

Can someone please help with continuous action example? What should the output format look like for continuous action space examples? Did anyone run pendulum example successfully? I tried running pendulum example but found errors.

**step 1:-**
**Generate Data**
python3 ml/rl/test/gym/run_gym.py -p <location>/ddpg_pendulum_v0_datagen.json -f <targetfolder>/training_data.json

**Generated Data format is as following (sample):-**
{"ds": "2019-01-01", 
"mdp_id": "99", 
"sequence_number": 179, 
"state_features": {"0": 0.7077672662018737, "1": -0.7064456786569835, "2": -1.4642522740018904}, 
"action": {"3": 1.9947617053985596}, 
"reward": -0.8337657799161808, 
"action_probability": 0.0, 
"possible_actions": null, 
"metrics": {"reward": -0.8337657799161808}}

**step 2**
**Call spark job to process the data using config example for continuous_actions**
{
  "timeline": {
    "startDs": "2019-01-01",
    "endDs": "2019-01-01",
    "addTerminalStateRow": false,
    "actionDiscrete": false,
    "inputTableName": "pendulum",
    "outputTableName": "pendulum_training",
    "evalTableName": "pendulum_eval",
    "numOutputShards": 1
  },
  "query": {
    "tableSample": 5
  }
}

**Here is the snippet of error  ..**

2019-04-09 19:27:01 INFO  FileScanRDD:54 - Reading File path: file:///oxygen/ec2-user/project/narasimham/Dynamic_pricing/horizon/pendulum_ctn/pendulum/training_data.json, range: 0-4194304, partition values: [empty row]
2019-04-09 19:27:01 INFO  FileScanRDD:54 - Reading File path: file:///oxygen/ec2-user/project/narasimham/Dynamic_pricing/horizon/pendulum_ctn/pendulum/training_data.json, range: 4194304-6500846, partition values: [empty row]
2019-04-09 19:27:01 ERROR Executor:91 - Exception in task 0.0 in stage 1.0 (TID 1)
org.apache.spark.SparkException: Failed to execute user defined function(anonfun$2: (array<map<string,double>>) => array<map<bigint,double>>)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:619)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
        at org.apache.spark.scheduler.Task.run(Task.scala:109)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192)
        at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192)
        at scala.collection.SeqLike$class.size(SeqLike.scala:106)
        at scala.collection.mutable.ArrayOps$ofRef.size(ArrayOps.scala:186)
        at scala.collection.mutable.Builder$class.sizeHint(Builder.scala:69)
        at scala.collection.mutable.ArrayBuilder.sizeHint(ArrayBuilder.scala:22)
        at scala.collection.TraversableLike$class.builder$1(TraversableLike.scala:230)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:233)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
        at com.facebook.spark.rl.Preprocessor$$anonfun$2.apply(Preprocessor.scala:67)
        at com.facebook.spark.rl.Preprocessor$$anonfun$2.apply(Preprocessor.scala:66)

Thanks,
Narasimha

**Comment by MisterTea** [comment]
Hey @NarasimhaM3101 !  We'll take a look at this later on this week.

**Comment by wsun66** [comment]
Any solution for the issue. I still got the exactly same error when running spark job to generate timeline data. I am using the latest master branch (Cloned on July 25, 2019). Thanks,

ws

**Comment by kaiwenw** [comment]
@wsun66 @NarasimhaM3101 we have an example SAC offline workflow, which is very similar to the DQN offline tutorial
