### ISSUE TITLE
Cannot build the timeline in the contextual bandit tutorial

### ISSUE THREAD

**Issue by amarchin** [facebookresearch/ReAgent#191]
I am currently trying to follow the the [tutorial](https://reagent.ai/rasp_tutorial.html#straight-outta-context). Everything worked fine until I tried to execute the Spark submit command
```
(base) root@262985aeb18b:~/ReAgent# rm -Rf spark-warehouse derby.log metastore_db preprocessing/spark-warehouse preprocessing/metastore_db preprocessing/derby.log ; /usr/local/spark/bin/spark-submit \
>   --class com.facebook.spark.rl.Preprocessor preprocessing/target/rl-preprocessing-1.1.jar \
>   "`cat serving/examples/ecommerce/training/timeline.json`"

2019-11-29 11:54:37 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Warning: Local jar /home/ReAgent/preprocessing/target/rl-preprocessing-1.1.jar does not exist, skipping.
java.lang.ClassNotFoundException: com.facebook.spark.rl.Preprocessor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:239)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:851)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2019-11-29 11:54:37 INFO  ShutdownHookManager:54 - Shutdown hook called
2019-11-29 11:54:37 INFO  ShutdownHookManager:54 - Deleting directory /tmp/spark-e105a6c2-15f8-4e11-a21b-98a3a84c38b5
```
I installed ReAgent using Docker (CPU only) on MacOS High Sierra.

**Comment by amarchin** [comment]
Ok, basically I need to run
```
# Build timeline package (only need to do this first time)
mvn -f preprocessing/pom.xml clean package
```
as it reported [here](http://reagent.ai/usage.html#step-2-convert-the-data-to-the-timeline-format). The tutorial for the contextual bandit needs to be updated.
