### ISSUE TITLE
Impossible to use CNN with image observation space

### ISSUE THREAD

**Issue by valeriopastore20** [facebookresearch/ReAgent#198]
I'm trying to run the example "discrete_dqn_maxq_asteroids_v0.json" in "ml/rl/test/gym". First i had the issue that there where 3 missing parameters in the json file, in particular they where "num_input_channels", "input_height" and "input_width". After I added them and run again I had this traceback:

Traceback (most recent call last):
File "ml/rl/test/gym/run_gym.py", line 912, in <module>
`main(args[1:])`
File "ml/rl/test/gym/run_gym.py", line 707, in main
`args.path_to_pickled_transitions,`
File "ml/rl/test/gym/run_gym.py", line 769, in run_gym
`trainer` = warm_trainer if warm_trainer else create_trainer(params, env)
File "ml/rl/test/gym/run_gym.py", line 822, in create_trainer
`discrete_trainer_params,` env.normalization, use_gpu
File "/home/valerio/ReAgent/ml/rl/workflow/transitional.py", line 79, in create_dqn_trainer_from_params
`state_dim=get_num_output_features(normalization_parameters),`
File "/home/valerio/ReAgent/ml/rl/preprocessing/normalization.py", line 183, in get_num_output_features
`normalization_parameters.values(),`
AttributeError: 'NoneType' object has no attribute 'values'

The problem seems to rely in the function "normalization" in "open_ai_gym_environment.py" that returns None if the observation turns out to be an image.

**Comment by kittipatv** [comment]
Image input is not implemented at the moment. However, it should work if you plug your own model at, https://github.com/facebookresearch/ReAgent/blob/ebc5ee35c1635f656cacd97efbf43dbdfcbc227e/ml/rl/workflow/transitional.py#L78.

**Comment by valeriopastore20** [comment]
> Image input is not implemented at the moment. However, it should work if you plug your own model at,
> 
> https://github.com/facebookresearch/ReAgent/blob/ebc5ee35c1635f656cacd97efbf43dbdfcbc227e/ml/rl/workflow/transitional.py#L78
> 
> .

I tried but the problem persists because of "state_dim=get_num_output_features(normalization_parameters)" called when creating the reward network, but the function "normalization" in "open_ai_gym_environment.py" returns None for images

**Comment by czxttkl** [comment]
Yes, open_ai_gym_environment.py also needs to be modified. Currently, it does not support well for image-based envs.
