### ISSUE TITLE
tensorboardX summarywriter file exist error in multiple GPU case

### ISSUE THREAD

**Issue by zhangruiskyline** [facebookresearch/ReAgent#214]
when we run in a one node 4 GPUs case, when our first start, sometimes we get file exist error. usually when we run next time, it get resolve.

but I wonder whether it is a tensorboard issue or ReAgent issue?

```
Traceback (most recent call last):
  File "/home/miniconda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/Horizon/ml/rl/workflow/dqn_workflow.py", line 104, in single_process_main
    writer = SummaryWriter(log_dir=os.path.join(os.getenv('HOME'), 'tensorboard', os.getenv('JOB_ID')'logs'))
  File "/home/miniconda/lib/python3.6/site-packages/tensorboardX/writer.py", line 279, in __init__
    self.file_writer = FileWriter(logdir=log_dir, **kwargs)
  File "/home/miniconda/lib/python3.6/site-packages/tensorboardX/writer.py", line 201, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "/home/miniconda/lib/python3.6/site-packages/tensorboardX/event_file_writer.py", line 108, in __init__
    directory_check(self._logdir)
  File "/home/miniconda/lib/python3.6/site-packages/tensorboardX/record_writer.py", line 43, in directory_check
    os.makedirs(path)
  File "/home/miniconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/tensorboard/73e910f9-24b9-41e9-b10e-aedf97ba47a6/logs'
```

**Comment by MisterTea** [comment]
That makes sense: there's probably a race condition in the tensorboardx constructor.  Is SummaryWriter picklable?  If so, maybe we pass the summarywriter to child processes.  If not, maybe creating a dummy SummaryWriter at the beginning would work (the race might just be when the file doesn't already exist)

**Comment by zhangruiskyline** [comment]
Thanks, is there a potential for this will be checked in pretty soon?

**Comment by MisterTea** [comment]
Can you try one of those solutions and see if it fixes the problem?  They are both small changes in https://github.com/facebookresearch/ReAgent/blob/master/ml/rl/workflow/dqn_workflow.py

**Comment by zhangruiskyline** [comment]
Thanks @MisterTea , can I know which fix has addressed this issue? we have modified the dqn_workflow , so would like to know which change address this issue and can fix in our side

**Comment by zhangruiskyline** [comment]
Hi @MisterTea 

I saw the change for SummaryWriter is to replace `from tensorboardX import SummaryWriter` with `from torch.utils.tensorboard import SummaryWriter`, will this lib update address this issue mentioned above?

**Comment by zhangruiskyline** [comment]
Hi @MisterTea , I got a `ModuleNotFoundError: No module named 'torch.utils.tensorboard'` even if I upgrade the `tensorboard `and `torch `module. so wonder which package should I use? and is it the key fix to address this problem?

**Comment by xumengen** [comment]
> when we run in a one node 4 GPUs case, when our first start, sometimes we get file exist error. usually when we run next time, it get resolve.
> 
> but I wonder whether it is a tensorboard issue or ReAgent issue?
> 
> ```
> Traceback (most recent call last):
>   File "/home/miniconda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
>     fn(i, *args)
>   File "/Horizon/ml/rl/workflow/dqn_workflow.py", line 104, in single_process_main
>     writer = SummaryWriter(log_dir=os.path.join(os.getenv('HOME'), 'tensorboard', os.getenv('JOB_ID')'logs'))
>   File "/home/miniconda/lib/python3.6/site-packages/tensorboardX/writer.py", line 279, in __init__
>     self.file_writer = FileWriter(logdir=log_dir, **kwargs)
>   File "/home/miniconda/lib/python3.6/site-packages/tensorboardX/writer.py", line 201, in __init__
>     logdir, max_queue, flush_secs, filename_suffix)
>   File "/home/miniconda/lib/python3.6/site-packages/tensorboardX/event_file_writer.py", line 108, in __init__
>     directory_check(self._logdir)
>   File "/home/miniconda/lib/python3.6/site-packages/tensorboardX/record_writer.py", line 43, in directory_check
>     os.makedirs(path)
>   File "/home/miniconda/lib/python3.6/os.py", line 220, in makedirs
>     mkdir(name, mode)
> FileExistsError: [Errno 17] File exists: '/home/tensorboard/73e910f9-24b9-41e9-b10e-aedf97ba47a6/logs'
> ```

I have met the same problem with you. I run on one node with 8 gpus, and then met this problem...

**Comment by DeepAlchemist** [comment]
solve this issue by 
`pip install 'git+https://github.com/lanpa/tensorboardX' `
