### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by simutisernestas** [facebookresearch/ReAgent#432]
```
Traceback (most recent call last):
  File "./reagent/workflow/cli.py", line 87, in <module>
    reagent()
  File "/home/ernestas/opt/miniconda/envs/py37/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ernestas/opt/miniconda/envs/py37/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ernestas/opt/miniconda/envs/py37/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ernestas/opt/miniconda/envs/py37/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ernestas/opt/miniconda/envs/py37/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./reagent/workflow/cli.py", line 75, in run
    func(**config.asdict())
  File "/home/ernestas/opt/miniconda/envs/py37/lib/python3.7/site-packages/reagent/workflow/gym_batch_rl.py", line 90, in timeline_operator
    call_spark_class(spark, class_name="Timeline", args=json.dumps(arg))
  File "/home/ernestas/opt/miniconda/envs/py37/lib/python3.7/site-packages/reagent/workflow/spark_utils.py", line 68, in call_spark_class
    spark_class.main(args)
TypeError: 'JavaPackage' object is not callable
```

Could you help with this?

**Comment by bobjer** [comment]
@simutisernestas Hi, could you please advise how to solve this?
